<a href="https://colab.research.google.com/github/PraveenBunker/45-days-of-python/blob/main/DAY13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Row operation in pandas***

* loc = row label/index ke basis par

* iloc = row number (position) ke basis par.

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
# single column ka data get krne k liye
df["name"]
# add single column

df["salary"] = df["marks"] + 100
# add single column
df["salary12"] = [100,200,300,400,500]


# # df
# print(df.iloc[2,0])
# print(df.iloc[0:3])
# print(df.loc[2,"name"])
# print(df.iloc[1])  #get single
# # print(df.loc[1:3,"name"]) get multiple rows
# print(df.loc[1])

# # sub data set using iloc
# df1 = df.iloc[0:2,[0]]
# df1

# sub data set using loc
df2 = df.loc[0:3,["marks","salary"]]
df2

# df

   marks  salary
0     10     110
1     20     120
2     30     130
3     40     140

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
print(df)

# print(df.iloc[2,3])
# print(df.iloc[0:3])
# print(df.loc[2,"Name"])
# print(df.iloc[1])  #get single



df1 = df.iloc[0:2,[0,1,2]]
df1

# df2 = df.loc[0:3,["Salary","Experience"]]
# df2

# print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

   Emp_ID  Name Department
0     101  Amit         IT
1     102  Riya         HR

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df  = pd.read_json(url)
# # df
df["maths"] = df["maths"] + 100
# df
#
# df1 = df.iloc[0:2,[0,1,2]]
# df1


# print(df.iloc[2,3])
# print(df.iloc[0:3])
# print(df.loc[2,"name"])
# print(df.iloc[1])  #get single






#filter

# df[df["english"] == 95]

# filter2
# df[df["maths"] < 160]


df[df["physics"] <= 56]


# maths 90 and english 90
# df[(df["maths"] > 190)& (df["english"] > 90)] #and
df[(df["maths"] > 190)| (df["english"] > 90)] #or

      name  gender  physics  maths  english
1   rajesh    Male       96    200       95
10   Gowri  Female      100    200      100